name: ourESchool
description: A School Management Project
publish_to: "none"
version: 1.0.0-dev.1.0.1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf_viewer_plugin: ^2.0.1
  camera: ^0.10.5+4
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.6
  custom_radio_grouped_button: ^2.2.0
  dio: ^5.3.2
  division: ^0.9.0
  file_picker: ^5.3.3
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.4
  http: ^1.1.0
  image: ^4.0.17
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  intl: ^0.18.1
  intro_views_flutter: ^3.2.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  flutter_randomcolor: ^1.0.14

  # random_color: ^1.0.5
  # ------------------------------------------------------
  shared_preferences: ^2.2.1
  file: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   rxdart: ^0.22.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Italic.ttf
